### PR TITLE
Repair the bug that multiple ips are gotten.

### PR DESCRIPTION
**Pull request by 5herhom**
Repair the bug that multiple ips are gotten instead of one when starting and installing.
Details see: [https://github.com/WeBankFinTech/DataSphereStudio/issues/96](url)

### CODE REVIEW

**Comment by liuzhimindluter** [comment]
谢谢大佬，测试了一下，OK了，不过我有个疑问，我想问一下直接拷贝是由于giuthub的问题，还是您上传的问题，中文逗号，中文分割，还有awk应该是小写

**Comment by peacewong** [comment]
@liuzhimindluter Hello, is it lowercase

**Comment by liuzhimindluter** [comment]
@peacewong yes,it needs lowercase 
ipaddr=$(ip addr | awk '/^[0-9]+：/ {}; /inet.*global/ {print gensub(/(.*)\/(.*)/, "\\1", "G",$2)}'|awk  'NR == 1')

**Comment by liuzhimindluter** [comment]
emm，抱歉，我检查了一下，我浏览器问题，直接转成中文另外

**Comment by liuzhimindluter** [comment]
谢谢大佬！

**Pull request merged**
